apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  VITE_API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
