apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "frontend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
