fullnameOverride: ""
replicaCount: 3
image:
  repository: acr.azurecr.io/backend
  tag: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 768Mi
livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 30
readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 10
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  cpuTargetPercentage: 60
envs:
  DATASOURCE_URL: ""
  DATASOURCE_USERNAME: ""
secrets:
  existingSecret: ""

azureWorkloadIdentity:
  clientId: ""
  tenantId: ""
