apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azureWorkloadIdentity.clientId | default "" | quote }}
    azure.workload.identity/tenant-id: {{ .Values.azureWorkloadIdentity.tenantId | default "" | quote }}
